; pads
; Pads : mask = xxxxxxCx xxBx2580 147*oxAP 369#RLDU
; U235 format
;------------------------------------------------------------- Joypad Section
; Pads : mask = xxxxxxCx xxBx2580 147*oxAP 369#RLDU

;	Bit numbers for buttons in the mask for testing individual bits
U235SE_BBUT_UP		EQU	 0	; Up
U235SE_BBUT_U		EQU	 0
U235SE_BBUT_DOWN	EQU	 1	; Down
U235SE_BBUT_D		EQU	 1
U235SE_BBUT_LEFT	EQU	 2	; Left
U235SE_BBUT_L		EQU	 2
U235SE_BBUT_RIGHT	EQU	 3	; Right
U235SE_BBUT_R		EQU	 3
U235SE_BBUT_HASH	EQU	 4	; Hash (#)
U235SE_BBUT_9		EQU	 5	; 9
U235SE_BBUT_6		EQU	 6	; 6
U235SE_BBUT_3		EQU	 7	; 3
U235SE_BBUT_PAUSE	EQU	 8	; Pause
U235SE_BBUT_A		EQU	 9	; A button
U235SE_BBUT_OPTION	EQU	11	; Option
U235SE_BBUT_STAR	EQU	12	; Star
U235SE_BBUT_7		EQU	13	; 7
U235SE_BBUT_4		EQU	14	; 4
U235SE_BBUT_1		EQU	15	; 1
U235SE_BBUT_0		EQU	16	; 0 (zero)
U235SE_BBUT_8		EQU	17	; 8
U235SE_BBUT_5		EQU	18	; 5
U235SE_BBUT_2		EQU	19	; 2
U235SE_BBUT_B		EQU	21	; B button
U235SE_BBUT_C		EQU	25	; C button

;				 Numerical representations
U235SE_BUT_UP		EQU	 1	; Up
U235SE_BUT_U		EQU	 1
U235SE_BUT_DOWN		EQU	 2	; Down
U235SE_BUT_D		EQU	 2
U235SE_BUT_LEFT		EQU	 4	; Left
U235SE_BUT_L		EQU	 4
U235SE_BUT_RIGHT	EQU	 8	; Right
U235SE_BUT_R		EQU	 8
U235SE_BUT_HASH		EQU	 16	 ; Hash (#)
U235SE_BUT_9		EQU	 32	 ; 9
U235SE_BUT_6		EQU	 64	 ; 6
U235SE_BUT_3		EQU	 $80	; 3
U235SE_BUT_PAUSE	EQU	 $100	 ; Pause
U235SE_BUT_A		EQU	 $200	 ; A button
U235SE_BUT_OPTION	EQU	 $800	 ; Option
U235SE_BUT_STAR		EQU	 $1000    ; Star
U235SE_BUT_7		EQU	 $2000    ; 7
U235SE_BUT_4		EQU	 $4000    ; 4
U235SE_BUT_1		EQU	 $8000    ; 1
U235SE_BUT_0		EQU	 $10000    ; 0 (zero)
U235SE_BUT_8		EQU	 $20000    ; 8
U235SE_BUT_5		EQU	 $40000    ; 5
U235SE_BUT_2		EQU	 $80000    ; 2
U235SE_BUT_B		EQU	 $200000    ; B button
U235SE_BUT_C		EQU	 $2000000; C button
